var GAME_LEVELS = [
  ["                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxx",
   "                                           ",
   "                                    o      ",
   "                                           ",
   "                                           ",
   " @              xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx    o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx                                xxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxx                    o             xxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxx                                      xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx                      xxx               xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx           o                              xxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxx                                            xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx                   xx            xx           xxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                            o   ",
   "                            x                                                   ",
   " @                                                         o                    ",
   "xxx                                                                         xxxx",
   "xxx                                                                          xxx",
   "xxx                  xxx                                                     xxx",
   "xxx                                                                          xxx",
   "xxx      b                                                           z       xxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx              xxxxx      xxxxxxxx   xxxxxxx                                   xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx               x!!!x      xxxxxxxx o xxxxxxx                                   xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxx                x!!!x      xxxxxxxx   xxxxxxx                                   xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx                 x!!!x      xxxxxxxx   xxxxxxx                                   xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxx                  x!!!x      xxx                                        o         xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx          o        x!!!x      xxx                                                  xxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                   x!!!!!x     xxx                                        x         xxxxxxxx",
   "xxxxxxxxxxxxxxxxx                     x!!!x      xxx                b                                 xxxxxxxx",
   "xxxxxxxxxxxxxxxx           xxxxx       xvx      xxxx     xxxxxxxxxxxxxxxxxxxx                         xxxxxxxx",
   "xxxxxxxxxxxxxxx            xxxxx               xxxxx     xxxxxx!!!!!!!!!!!!!x         x               xxxxxxxx",
   "xxxxxxxxxxxxxx             xxxxx        o     xxxxxxx    xxxxxxx!!!!!!!!!!!!x                         xxxxxxxx",
   "xxxxxxxxxxxxx              xxxxx                         xxxxxxxx!!!!!!!!!!!x                         xxxxxxxx",
   "                o   xx     xxxxx                         xxxxxxxxx!!!!!!!!!!x                                 ",
   "                           xxxxx                          xxxxxxxxx!!!!!!!!!x                         o       ",
   "                           xxxxx                xxxxxxx   xxxxxxxxxx!!!!!!!!x       x                         ",
   " @                         xxxxx                x!!!!!x            x!!!!!!!!x                   x             ",
   "xxxxx        xx!!!!!!!!!!!!!!!!x                x!!!!!x        o  x!!!!!!!!!x                          xxxxxxx",
   "!!!!x        x!!!!!!!!!!!!!!!!!x                x!!!!!x          x!!!!!!!!!!x                            xxxxx",
   "!!!!x    o   x!!!!!!!!!!!!!!!!!xxxxxx       xxxxx!!!!!xxxxxxxxxxx!!!!!!!!!!!x                x           xxxxx",
   "!!!!x        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                            xxxxx",
   "!!!!x        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                            xxxxx",
   "!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           b                xxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                     x!!!!!!!!!!!!!!x              o                        xxxxxxxxxxxxxxxxxx",
   "                                      x!!!!!!!!!!!!x                                        xxxxxxxxxxxxxxxxxx",
   " @                                     x!!!!!!!!!!x    xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "xxxxxx                     xxx     xxxxxxxxxxxxxxx    x                        x!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!x          o          x         x               x                          x!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!x                     x         x     o        x     o                o     x!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!x                   x    o    x              x            x     x           x!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!xx      xxx      xx         x     xxxxx    xxxxxxxxxxxxxxx     xxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!x               x         x     x!!!!!x                                  x!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!x             x         x     x!!!!!!!x                                x!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!x           x         x     x!!!!!!!!!x                     b        x!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!x         x    o    x     x!!!!!!!!!!!x          xxxxxxxxxxxxxx    x!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!x   o   x         x     xxxxxxvxxxxxxxxx         x!!!!!!!!!!x    x!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!x     x         x   o                  x         x!!!!!!!!x    x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!xxxxx         x                        x    o    x!!!!!!x    x!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x       xxxxxxxxxxxx                x         x!!!!x    x!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x              o  x         xxxx    x!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x                  x               x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x                   x             xxxvxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x                    xxxxxxxxxx                                          ",
   "!!!!!!!!!!!!!!!!!!xo       x!!!!!!!!!xx      o      x      x!!!!!!x                                     o     ",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x                    x!!!!!!x                                            ",
   "!!!!!!!!!!!!!!!!!!xx       x!!!!!!!!!x                   x!!!!!!x                             xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x                 xx!!!!!!x              o               xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x       x         x!!!!!!x                               xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x       xxxxxxxxxxxx                x!!!!!!x                                xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x                                  x!!!!!!x       b                         xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x                                 x!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!x                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!x                       b       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx      xx!!!!!!!!!!x             x!!!!!!!!x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx    o xx!!!!!!!!!!x      o      x!!!!!!!!x   o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx        xx!!!!!!!!!!x             x!!!!!!!!x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx     xxxxx!!!!!!!!!!=             !!!!!!!!!x                            xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx     xxxxx!!!!!!!!!!x             x!!!!!!!!x                            xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx     xxxxx!!!!!!!!!!x             x!!!!!!!!x      xxxxxxxxxxxxxxxxx                       x",
   "                        xxxxxxxxxxxxxxxx     xxx     xxxxxxxxxx      xx!!!!!!!!xxo                           x",
   "                        xxxxx                                       xxx!!!!!!!!xx         xxxxxxxxxxxxxx     x",
   " @                     xxxxxx  o                                     xx!!!!!!!!xx          xxxxxxxxxxxxxx    x",
   "xxxxxxxxxxxxxxxxxxx                       x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxx    x",
   "xxxxxxxxxxxxxxxxxxx                                 xx  o                                  xxxxxxxxxxxxxx    x",
   "xxxxxxxxxxxxxxxxxxx    xxxxxxx                      xx                                    xx     o          xx",
   "xxxxxxxxxxxxxxxxxxx    xx!!!xx         x            xxxx               z                   x                 x",
   "xxxxxxxxxxxxxxxxxxx    xx!!!xx                      xx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!=                 x",  
   "xxxxxxxxxxxxxxxxxxx    xxxxxxx      x               xxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxx",  
   "   o     o     o       x     x                                                                     xxxxxxxxxxx",
   "                       x  o  x                                                                     xxxxxxxxxxx", 
   "                       x     xxxxxx           x                                                    xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx                                                                           o    xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx                                                  xxxx             xxxx         xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx        b                 z                       xxxx      b      xxxx         xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx                             xxxxxxxxx",
   "xxxxx                             xxxxxxxxx",
   "                                  xxxxxxxxx",
   "                                  xxxxxxxxx",
   " @                 h              xxxxxxxxx",
   "xxxxx                             xxxxxxxxx",
   "xxxxx                             xxxxxxxxx",
   "xxxxx                             xxxxxxxxx",
   "xxxxx            xxxxxx           xxxxxxxxx",
   "xxxxx            xxxxxx           xxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
